name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Analysing the code with flake8
      run: |
        python -m flake8 --max-line-length=88 evobench
    - name: Tests
      run: |
        coverage run -m pytest evobench
        coverage report --include=evobench/**
        coverage html --include=evobench/**

    # - name: Analysing the code with pylint
    #   run: |
    #     pylint `ls -R|grep .py$|xargs`
